config/routes.rb
Rails.application.routes.draw do
  root "citizens#index"
  resources :addresses
  resources :citizens
  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :citizen

  validates :zip_code, :street, :district, :city, :UF, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citizen.rb
class Citizen < ApplicationRecord
  has_one :address
  before_validation :only_digit

  STATUS = %w[ativo desativado]

  accepts_nested_attributes_for :address, allow_destroy: true


  validates :full_name, :cpf, :birth_date, :email, :telephone, presence: true
  validates_format_of :full_name, with: FULL_NAME_FORMAT
  validates :cpf, :email, uniqueness: true
  validates_format_of :email, with: EMAIL_FORMAT
  validates_format_of :cpf, with: /\A.[0-9]+\z/
  validates_length_of :cpf, is: 11
  validates :status, presence: true, inclusion: { in: STATUS }
  mount_uploader :image, ImageUploader

  def only_digit
    cpf.gsub!(/[^\d]/, '')
  end
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  validates_presence_of :name
end

app/models/state.rb
class State < ApplicationRecord
  validates_presence_of :name, :abbr
  validates :abbr, :length => { :is => 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  validates_format_of :email, with: EMAIL_FORMAT
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:zip_code, :street, :complement, :district, :city_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  before_action :authenticate_user!
  before_action :set_citizen, only: %i[ show edit update destroy ]
  layout 'citizen_layout'

  def index
    @search = Citizen.ransack(params[:q])
    @pagy, @citizens = pagy(@search.result())
  end

  def show
  end

  def new
    @citizen = Citizen.new
    @citizen.build_address
  end

  def edit
  end

  def create
    @citizen = Citizen.new(citizen_params)

    if @citizen.save
      redirect_to @citizen, notice: t('notice.title.new')
      SendNotificationWelcome.new(@citizen).execute
    else
      render :new, status: :unprocessable_entity
    end

  end

  def update
    if @citizen.update(citizen_params)
      redirect_to @citizen, notice: t('notice.title.edit')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_citizen
      @citizen = Citizen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def citizen_params
      params.require(:citizen).permit(:full_name, :cpf, :email, :birth_date, :telephone, :image, :status,
                                      address_attributes: [:id, :zip_code, :street, :complement, :district, :city, :ibge, :UF])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/citizens_helper.rb
module CitizensHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :complement %>
    <%= form.text_field :complement %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Zip code</th>
      <th>Street</th>
      <th>Complement</th>
      <th>District</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.zip_code %></td>
        <td><%= address.street %></td>
        <td><%= address.complement %></td>
        <td><%= address.district %></td>
        <td><%= address.city_id %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip code:</strong>
  <%= @address.zip_code %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @address.complement %>
</p>

<p>
  <strong>District:</strong>
  <%= @address.district %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city_id %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/citizens/_form.html.erb
<%= form_with(model: citizen) do |form| %>
  <% if citizen.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.body')%></h2>

      <ul>
        <% citizen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-label-group col-md-6">
      <%= form.text_field :full_name, autofocus: true, class: "form-control", placeholder: "  " %>
      <%= form.label :full_name %>
    </div>

    <div class="form-label-group col-md-6" >
      <%= form.text_field :cpf, autofocus: true, class: "form-control", placeholder: "   ",  'data-mask': '000.000.000-00' %>
      <%= form.label :cpf %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-label-group col-md-6">
      <%= form.text_field :email , autofocus: true, class: "form-control", placeholder: "   "%>
      <%= form.label :email %>
    </div>

    <div class="form-label-group col-md-6" >
      <%= form.date_field :birth_date, autofocus: true, class: "form-control", placeholder: "   "%>
      <%= form.label :birth_date %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-label-group col-md-6">
      <%= form.text_field :telephone, autofocus: true, class: "form-control", placeholder: "   ",  'data-mask': '+55(00)00000-0000' %>
      <%= form.label :telephone %>
    </div>

    <div class="col-md-6">
      <div class="input-group mb-3">
        <%= form.file_field :image, autofocus: true, placeholder: "   ", class: "custom-file-input", id: "inputGroupFile03", aria_describedby:"inputGroupFileAddon03"%>
        <%= form.label :image, class: "custom-file-label", for: "inputGroupFile03" %>
      </div>
    </div>

    <div class="form-label col-md-6" >
      <%= label_tag nil, @citizen.class.human_attribute_name(:status) %> <br/>
      <%= form.select :status, [["Ativo", "ativo"], ["Inativo", "desativado"]], placeholder: "  "  %>
    </div>
  </div>

  <h4>Endereço</h4>
  <%= form.fields_for :address do |address_form| %>
    <div class="form-row">
      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :zip_code, class: "form-control cep", placeholder: "  "%>
        <%= address_form.label :zip_code %>
      </div>

      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :street, autofocus: true, class: "form-control", placeholder: "  " %>
        <%= address_form.label :street %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :complement, autofocus: true, class: "form-control", placeholder: "   " %>
        <%= address_form.label :complement %>
      </div>

      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :district, autofocus: true, class: "form-control", placeholder: "   " %>
        <%= address_form.label :district %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :city, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "   " %>
        <%= address_form.label :city %>
      </div>

      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :UF, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "   " %>
        <%= address_form.label :UF %>
      </div>

      <div class="form-label-group col-md-6" >
        <%= address_form.text_field :ibge, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "   "%>
        <%= address_form.label :ibge %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <%= render 'citizens/buttons/save' %>
    <%= render 'citizens/buttons/back' %>
  </div>
<% end %>

app/views/citizens/buttons/_back.html.erb
<%= link_to citizens_path, class: "btn btn-primary btn-circle", title: t('buttons.back') do %>
  <i class="fas fa-step-backward"></i>
<% end %>

app/views/citizens/buttons/_edit.html.erb
<%= link_to edit_citizen_path(@citizen), class:"btn btn-link btn-circle", title: t('buttons.edit') do %>
  <i class="fas fa-user-edit"></i>
<% end %>

app/views/citizens/buttons/_save.html.erb
<button type="submit" class="btn btn-facebook btn-primary btn-circle" title=<%= t('buttons.save') %>>
  <i class="fas fa-save"></i>
</button>

app/views/citizens/buttons/_show.html.erb
<%= link_to @citizen, class:"btn btn-link btn-circle", title: t('buttons.show') do %>
   <i class="far fa-eye"></i>
<% end %>

app/views/citizens/edit.html.erb
<h1><%= t('titles.edit', model: @citizen.model_name.human) %></h1>


<div class="card">
  <%= render 'form', citizen: @citizen %>
</div>

app/views/citizens/index.html.erb
<div class="container">
  <h1><%= t('titles.listing', model: @citizens.model_name.human(count: 2)) %></h1>

  <div class="form-row">
    <div class="col-md-6 mb-3"></div>
    <div class="col-md-3 mb-3 text-right">
      <%= link_to new_citizen_path, class:"btn btn-success btn-circle" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    </div>
    <div class="col-md-3 mb-3">
      <%= search_form_for @search do |f| %>
          <div class="input-group mb-3">
            <%= f.search_field :full_name_cont, autofocus: true, class: "form-control", placeholder: "Pesquisa Nome.." %>
            <button class="btn btn-primary" type="submit" name="action" >
              <i class="fas fa-search"></i>
            </button>
          </div>
      <% end %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered text-center" >
      <thead class="thead-dark">
      <tr>
        <th scope="col"> <%= @citizens.human_attribute_name('full_name') %></th>
        <th scope="col"> <%= @citizens.human_attribute_name('cpf') %></th>
        <th scope="col"> <%= @citizens.human_attribute_name('Email')%></th>
        <th scope="col"> <%= @citizens.human_attribute_name('birth_date')%></th>
        <th scope="col"> <%= @citizens.human_attribute_name('telephone')%></th>
        <th scope="col"> <%= @citizens.human_attribute_name('status')%></th>
        <th colspan="2"> Açoes </th>
      </tr>
      </thead>

      <tbody>
      <% @citizens.each do |citizen| %>
        <tr>
          <td><%= citizen.full_name %></td>
          <td><%= citizen.cpf %></td>
          <td><%= citizen.email %></td>
          <td><%= l citizen.birth_date %></td>
          <td><%= citizen.telephone %></td>
          <td><%= citizen.status %></td>
          <td> <%= link_to citizen, class:"btn btn-link btn-circle" do %>
              <i class="far fa-eye"></i>
            <% end %></td>
          <td><%= link_to edit_citizen_path(citizen), class:"btn btn-link btn-circle" do %>
              <i class="fas fa-user-edit"></i>
            <% end %></td>

        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


  <%== pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/citizens/new.html.erb
<h1><%= t('titles.new', model: @citizen.model_name.human) %></h1>

<div class="card">
  <%= render 'form', citizen: @citizen %>
</div>

app/views/citizens/show.html.erb
<div class="w-0">
  <form class="card-body card">
    <div class="row">
      <div class="col-md-1">
        <%= image_tag(@citizen.image_url(:thumb).to_s) %>
      </div>
      <div class="col-ms-1">
        <strong>
          <h3> <%= @citizen.full_name %> </h3>
        </strong>
      </div>

    </div>

    <div>
      <h5> Detalhes: </h5>

     <!-- <ul>
        <li> <%#= "#{@citizen.class.human_attribute_name(:cpf)}: #{@citizen.cpf}" %> </li>
        <li> <%#= "#{@citizen.class.human_attribute_name(:email)}: #{@citizen.email}" %> </li>
        <li> <%#= "#{@citizen.class.human_attribute_name(:birth_date)}: #{@citizen.birth_date}" %> </li>
        <li> <%#= "#{@citizen.class.human_attribute_name(:status)}: #{@citizen.status}" %> </li>
      </ul>-->

      <div class="form-group">
        <%= label_tag nil, @citizen.class.human_attribute_name(:cpf) %>
        <%= text_field_tag nil, @citizen.cpf, class:"form-control", disabled: true, 'data-mask': '000.000.000-00' %>
      </div>

      <div class="form-group">
        <%= label_tag nil, @citizen.class.human_attribute_name(:email) %>
        <%= text_field_tag nil, @citizen.email, class:"form-control", disabled: true %>
      </div>

      <div class="form-group">
        <%= label_tag nil, @citizen.class.human_attribute_name(:birth_date) %>
        <%= text_field_tag nil, l(@citizen.birth_date), class:"form-control", disabled: true %>
      </div>

      <div class="form-group">
        <%= label_tag nil, @citizen.class.human_attribute_name(:status) %>
        <%= text_field_tag nil, @citizen.status, class:"form-control", disabled: true %>
      </div>

      <h5> Endereço: </h5>
      <div class="row">
        <div class="form-group col-md-2">
          <%= label_tag nil, Address.human_attribute_name(:zip_code) %>
          <%= text_field_tag nil, @citizen.address.zip_code, class:"form-control cep", disabled: true %>
        </div>

        <div class="form-group col-md-6">
          <%= label_tag nil, Address.human_attribute_name(:street) %>
          <%= text_field_tag nil, @citizen.address.street, class:"form-control", disabled: true %>
        </div>

        <div class="form-group col-md-4">
          <%= label_tag nil, Address.human_attribute_name(:complement) %>
          <%= text_field_tag nil, @citizen.address.complement, class:"form-control", disabled: true %>
        </div>

        <div class="form-group col-md-4">
          <%= label_tag nil, Address.human_attribute_name(:district) %>
          <%= text_field_tag nil, @citizen.address.district, class:"form-control", disabled: true %>
        </div>

        <div class="form-group col-md-4">
          <%= label_tag nil, Address.human_attribute_name(:city) %>
          <%= text_field_tag nil, @citizen.address.city, class:"form-control", disabled: true %>
        </div>

        <div class="form-group col-md-2">
          <%= label_tag nil, Address.human_attribute_name(:UF) %>
          <%= text_field_tag nil, @citizen.address.UF, class:"form-control", disabled: true %>
        </div>
      </div>

    <%= render 'citizens/buttons/back' %>
    <%= render 'citizens/buttons/edit' %>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CitizenControl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href = "https://fonts.googleapis.com/icon?family=Material+Icons" rel = "stylesheet">
  </head>

  <body>
  <header>
    <% if user_signed_in? %>
      <%= render "shared/navbar"%>
    <% end %>
  </header>

  <main>
    <div class="container-fluid">
      <div class="container">
        <div class="row">
          <div class="col-sm-9 col-md-7 col-lg-6 mx-auto">
            <em class="alert-primary"><%= notice %></em>
            <em class="alert-danger"><%= alert %></em>
            <div class="card card-signin my-5">
              <div class="card-body">

                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  <div>
    <%= render "shared/footer" %>
  </div>


  </body>
</html>

app/views/layouts/citizen_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CitizenControl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= stylesheet_pack_tag 'application', media: 'all'%>
    <link href = "https://fonts.googleapis.com/icon?family=Material+Icons" rel = "stylesheet">
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= render "shared/navbar"%>
      <% end %>
    </header>

    <main>
      <div class="container-fluid">
        <div class="container">
          <div class="row">
              <div class="card-body">
                <em class="alert-primary"><%= notice %></em>
                <em class="alert-danger"><%= alert %></em>
                <%= yield %>
              </div>
          </div>
        </div>
      </div>
    </main>
    <div>
      <%= render "shared/footer" %>
    </div>


    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<section class="copyright py-5 text-center text-light bg-transparent">
  <div class="container-fluid">
    <small class="text-center text-black-50"><strong>Copyright &copy; OM30 2021</strong></small>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">

  <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path do %>
          <%= image_tag "logo", size: "60x60", class: "img-thumbnail"%>
        <% end %>
      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <li class="navbar-brand nav-item">
        <%= link_to destroy_user_session_path, class:"nav-link btn btn-danger", method: :delete do%>
          <i class="fa fa-sign-out"></i>
        <% end %>
      </li>
    </form>
  </div>
</nav>